spring.application.name=padelplanning

spring.datasource.url=jdbc:h2:mem:padelplanning
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.web.locale=nl-NL

security.h2-console-needed=true

#Properties for mailing sandbox mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=dacefe2cd6ad69
spring.mail.password=21b148d2b747b7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true